export const actionsTypes = {
  ADD_PROFORMA: "ADD_PROFORMA",
  FILTER_PROFORMA_LIST_BY_NAME: " FILTER_PROFORMA_LIST_BY_NAME",
  SET_PROFORMA_LIST: "SET_PROFORMA_LIST",
  SELECT_PROFORMA: "SELECT_PROFORMA",
};
